package exceptionTest;

public class ThrowTest {
	public static void main(String[] args) {
		
		System.out.println("예외발생시킬거야");
		
		throw new NumberFormatException();
//		System.out.println("출력문끝");
	}
}
